version: '3.8'

services:
  app:
    # Build the Docker image from the Dockerfile in the current directory
    build:
      context: .
      args:
        # Pass through API key so Vite can inline it at build time
        GEMINI_API_KEY: ${GEMINI_API_KEY}
    # Name the container for easier management
    container_name: gemini-productivity-tracker
    # Map host port 9090 to container port 80
    ports:
      - "9090:80"
    # Load envs (e.g., GEMINI_API_KEY) for build args substitution
    env_file:
      - .env
    # Automatically restart the container if it stops, unless manually stopped
    restart: unless-stopped